### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/devhatt-lp#2]
### Olá, desenvolvedor(a)!

Estamos empolgados com sua contribuição para a criação de mais uma lp fantástica!

### Sobre a Tarefa
**Objetivo:**
Criar o componente da imagem em questão utilizando as seguintes tecnologias.
_**Html, Vanillajs, Sass e Jest.**_

<img width="1176" alt="Screenshot 2024-01-04 at 18 06 46" src="https://github.com/devhatt/landing-pages/assets/17785028/ec8370c2-c1e0-4527-bc9f-08ca684b892e">

**Passos:**

Clone o repositório: `git clone https://github.com/devhatt/landing-pages`
Navegue até o diretório do projeto: `cd lading-pages/projects/petdex`
Instale as dependências: `pnpm install`

_O projeto esta em um monorepo então tambem terá acesso às demais lps existentes .
Certifique-se de usar apenas o que esta na sua task, do contrário seu pr sera rejeitado._

Crie o componente principal no diretório apropriado.

Dúvidas e Colaboração:

### DOCS:

[Figma:](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&mode=design)

Dúvidas? abra uma [discussion](https://github.com/devhatt/landing-pages/discussions)

Agradecemos sua contribuição para tornar o Petdex incrível! 🚀

**Comment by Frompaje** [comment]
Eu quero!!!
